sudo: false
dist: trusty
language: node_js

node_js:
  - "node"

before_install:
  - npm install -g npm

script:
  - npm install
  - npm rebuild node-sass
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: main
